### PR TITLE
Implement scan filter logic for Android 4.x and 5.x

### PR DESCRIPTION
**Pull request by jessejiang0214**
I have tested with 16bit UUID and 128bit custom UUID

### CODE REVIEW

**Comment by aritchie** [comment]
I appreciate the PR, however, I'm likely going to decline it since I already have an ad parsing mechanism further down the pipeline.  I also think the scan filters don't help perf at all and I'm likely to move all service UUID filtering up to the observable itself.

**Comment by jessejiang0214** [comment]
It's OK, but I found a problem is the advertisement bytes are different from StartLeScan and BluetoothLeScanner.StartScan API

**Comment by aritchie** [comment]
Give 5.3 a try

**Comment by jessejiang0214** [comment]
I have tested v5.3. It doesn't work. I go through the source code, something wrong with this function 
        protected bool IsFiltered(AdvertisementData ad, ScanConfig config)
        {
            if (config.ServiceUuids == null ||
                !config.ServiceUuids.Any() ||
                ad.ServiceUuids == null ||
                !ad.ServiceUuids.Any())
                return true;

            foreach (var adUuid in ad.ServiceUuids)
            {
                foreach (var uuid in config.ServiceUuids)
                {
                    if (uuid.Equals(adUuid))
                        return true;
                }
            }

            return false;
        }


There are two types of services UUID, one is 128-bit, which is normal, another is 16bit. In AdvertisementData, if UUID is 128-bit it can be found, but if it is 16 bit, it just shows the short one, like 02-FE-00 or 03-FE-00. In my code there is a function to handle this. You can use it if you want.

**Pull request closed without merging**
