### PR TITLE
Fixed System.InvalidOperationException in Disconnect()

### PR DESCRIPTION
**Pull request by MKGNZ**
Fixed exception System.InvalidOperationException "Collection was modified; enumeration operation may not execute."

### CODE REVIEW

**Comment by aritchie** [comment]
While I am happy to take this PR, you should know that this doesn't really fix anything.  As I mentioned in your issue, disconnect currently does not work.  You should just trap the error and hide accordingly.  I have filed an issue with Microsoft to see what I can do about this for which I have yet to get a response.

**Comment by MKGNZ** [comment]
Yes I know But I don't like wrapping my code in `if (Xamarin.Forms.Device.RuntimePlatform != Xamarin.Forms.Device.UWP)` just to avoid a call.

Also I have 1 more PR with the implementations of GetConnectedDevices(), GetKnownDevice() and GetPairedDevices()

**Comment by MKGNZ** [comment]
New update with implementation of GetConnectedDevices(), GetKnownDevice() and GetPatiredDevies()

**Comment by aritchie** [comment]
Great PR - thanks for the contribution.  I'll get this in as part of 6.1

**Pull request merged**
