### PR TITLE
UWP

### PR DESCRIPTION
**Pull request by StrangerUA**
Multiple reconnects working
Client able to disconnect

### CODE REVIEW

**Comment by aritchie** [comment]
Thanks for the PR.  While this likely fixes your issue, Scan is suppose to clear the context when starting a new one which I can see it is not.  I will patch this.

However, device reconnects are handled internally on the device.  It does not (and should not) remove itself from the context.

**Comment by StrangerUA** [comment]
proper fix for #246 is not working( 

I use 1 background scan in my app which never ends.
When I power off the device and power it back on it does not reconnect

**Comment by aritchie** [comment]
I haven’t worked at all with uwp ble in the background.  Can you provide a sample of your case that I can with?  

The case I’ve fixed is set for foreground properly and behaves like the other platforms so I don’t want to work outside of that.  Also, the bg service you’re running is external to the library.  I would rather integrate background support directly into the library

**Comment by StrangerUA** [comment]
I start scan at startup and never dispose it:
CrossBleAdapter.Current.Scan().Subscribe(onDeviceFound);
I have a blacklist feature, and on blacklisting connected module I dispose all characteristicsScans and call device.CancelConnection();
It also checks if device is blacklisted or not with condition in onDeviceFound action.

After that BLE device indicates disconnected state almost instantly. But it does not appear in scan results anymore. 
Using my fix It connects instantly.

My fix also helps when device is out of range or powered off and then returns in range or powered on again. 
My fix allows to handle all these cases with only 1 scan

**Comment by StrangerUA** [comment]
@aritchie Any chance to merge my fix?
I will fork if it is not possible to match my needs.

**Comment by aritchie** [comment]
@StrangerUA I am considering adding it still.  I was just hoping to do this a different way.

**Comment by aritchie** [comment]
The remove portion of adaptercontext/devicecontext has been added as part of 6.2.3.  Thanks for the PR

**Pull request closed without merging**
