### PR TITLE
Fix for manufacturerdata on android and null check

### PR DESCRIPTION
**Pull request by csteeg**

### CODE REVIEW

**Comment by aritchie** [comment]
Thanks for the PR.  Please try and keep them to just the actual feature in the future.  I'll decline the PR instead of cherrypicking.  Have you tested this App-Prefs with the sample app?

**Comment by csteeg** [comment]
Removed some commits, didn't work as expected anyway :(
It opened bluetooth settings only if that was the previous selected item in settings... so it just opens the settings on ios, not going to anything in the settings menu

**Comment by aritchie** [comment]
I appreciate the PR, but I think at this point, it has gone outside of the original intent.  Also, if you could leave the project settings (version, etc) out in any future PR's, it would be appreciated.

**Comment by csteeg** [comment]
I agree it's gone outside of the original intent, it are just some small fixes I needed now as I went along with my project. The largest change is to throw an exception on connection failure, so one can catch that in the app. In the current production release, connection failures on android just disappear (I had a lot of problems with PackageTooLarge exceptions).

**Pull request closed without merging**
